# Generated by Django 4.0.6 on 2022-07-21 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicar.horario')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicar.medico')),
            ],
            options={
                'unique_together': {('medico', 'dia', 'horarios')},
            },
        ),
    ]
