# Generated by Django 4.0.6 on 2022-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0004_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='agendado',
            field=models.BooleanField(default=False),
        ),
    ]
