# Generated by Django 4.0.6 on 2022-07-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0005_horario_agendado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='medicar.agenda'),
        ),
    ]
